# This workflow will install Python dependencies, run test_ and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Update README.md

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.10
      uses: actions/setup-python@v2
      with:
        python-version: "3.10"
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install flake8 pytest
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

    - name: Update analysis notebook
      run: |
        python -m pip install jupyter nbconvert nbformat
        jupyter nbconvert --to markdown --execute notebooks/introduction-to-Tiny-AutoML.ipynb --ExecutePreprocessor.kernel_name='python3' --NbConvertApp.output_files_dir='../ressources' --output README.md
    
    - name: Move readme file
      run: |
        mv notebooks/README.md README.md
        
    - name: commit updated notebook
      uses: EndBug/add-and-commit@v7
      with:
        author_name:  readme update bot
        message: "Update README.md"
        add: "notebooks/README.md, ressources"
